// Angular/ui/components/AgentQA.tsx
import React, { useState, useRef, useEffect } from 'react';
import {
  Send,
  Bot,
  User,
  HelpCircle,
  Clock,
  Sparkles,
  Search,
  MessageSquare,
  FileText,
  Upload,
} from 'lucide-react';
import { ChatMessage, SearchResultChunk } from '../types/rag';
import { sendRagQuery } from '../services/api';

interface AgentQAProps {
  onNavigateToDocs: () => void;
  documentCount: number;
  onErrorOccurred?: (err: any) => void;
}

export const AgentQA: React.FC<AgentQAProps> = ({
  onNavigateToDocs,
  documentCount,
  onErrorOccurred,
}) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'init-msg',
      role: 'agent',
      text: `Hello! I am your Enterprise AI Agent powered by .NET 9, MS SQL Server 2025 Vector Engine, and Gemini AI.

**Workflow when you send a message:**
1. **Vector Conversion**: Your prompt is converted to a 768-dimensional vector embedding.
2. **MS SQL Vector Search**: Queries our MS SQL Server database to fetch existing vectors and compute cosine similarity (\`VECTOR_DISTANCE('cosine')\`).
3. **Gemini LLM Prompting**: The retrieved vector context is passed to Gemini 3.8 Flash.
4. **Answer & Clarification**: An authoritative, grounded response is generated with source citations, and I will proactively ask clarifying questions if needed!`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    },
  ]);

  const [inputQuery, setInputQuery] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [topK, setTopK] = useState(4);
  const [minSimilarity, setMinSimilarity] = useState(0.2);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSend = async (queryToSend?: string) => {
    const query = (queryToSend || inputQuery).trim();
    if (!query || isLoading) return;

    setInputQuery('');

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      text: query,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, userMsg]);
    setIsLoading(true);

    try {
      const historyPayload = messages
        .filter((m) => m.id !== 'init-msg')
        .slice(-6)
        .map((m) => ({
          role: m.role,
          text: m.text,
        }));

      const response = await sendRagQuery(query, topK, minSimilarity, historyPayload);

      const agentMsg: ChatMessage = {
        id: `agent-${Date.now()}`,
        role: 'agent',
        text: response.answer,
        clarification: response.clarificationQuestion,
        retrievedChunks: response.retrievedChunks,
        sqlExecutionQuery: response.sqlExecutionQuery,
        searchTimeMs: response.searchTimeMs,
        llmTimeMs: response.llmTimeMs,
        modelUsed: response.modelUsed,
        confidenceScore: response.confidenceScore,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      };

      setMessages((prev) => [...prev, agentMsg]);
    } catch (err: any) {
      if (onErrorOccurred && err.type) {
        onErrorOccurred(err);
      }
      const errorMsg: ChatMessage = {
        id: `error-${Date.now()}`,
        role: 'agent',
        text: `⚠️ **${err.title || 'Error connecting to RAG backend'}**\n\n${err.message || 'Unknown error'}\n\n👉 *Remediation:* ${err.remediation || 'Please verify that the .NET API and MS SQL Server are running.'}`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleClarificationClick = (clarificationText: string) => {
    handleSend(`Regarding your question: "${clarificationText}" - please provide full details and standard policy recommendations.`);
  };

  const starterPrompts = [
    'What is our disaster recovery RPO and RTO SLA target?',
    'How many weeks of fully paid parental leave are primary caregivers entitled to?',
    'What is the network isolation protocol during a security breach?',
    'What wellness stipends and remote allowances do employees receive?',
  ];

  return (
    <div className="flex flex-col h-[740px] bg-white rounded-2xl border border-slate-200/80 shadow-xs overflow-hidden">
      {/* Agent Header */}
      <div className="p-4 bg-slate-900 text-white flex flex-wrap items-center justify-between gap-3 border-b border-slate-800">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-indigo-500 to-rose-500 p-0.5 flex items-center justify-center shadow-sm">
            <div className="w-full h-full bg-slate-900 rounded-[10px] flex items-center justify-center">
              <Bot className="w-5 h-5 text-indigo-400" />
            </div>
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm sm:text-base font-bold text-white">
                Agent Q&amp;A (Vector + Gemini)
              </h2>
              <span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                Live RAG
              </span>
            </div>
            <p className="text-[11px] text-slate-400">
              Query &rarr; Vectorize &rarr; MS SQL Cosine Search &rarr; Gemini LLM &rarr; Answer &amp; Clarification
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3 text-xs">
          <div className="flex items-center gap-2 bg-slate-800/80 px-2.5 py-1.5 rounded-lg border border-slate-700/80">
            <Search className="w-3.5 h-3.5 text-slate-400" />
            <span className="text-slate-400">Top-K:</span>
            <select
              value={topK}
              onChange={(e) => setTopK(Number(e.target.value))}
              className="bg-slate-900 text-slate-200 rounded px-1.5 py-0.5 text-xs border border-slate-700 font-mono"
            >
              <option value={2}>2 chunks</option>
              <option value={4}>4 chunks</option>
              <option value={6}>6 chunks</option>
            </select>
          </div>

          <button
            onClick={onNavigateToDocs}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white font-medium text-xs transition cursor-pointer"
          >
            <Upload className="w-3.5 h-3.5" />
            <span>Upload Files</span>
          </button>
        </div>
      </div>

      {/* Messages Stream */}
      <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-5 bg-slate-50/50">
        {messages.map((msg) => {
          const isUser = msg.role === 'user';
          return (
            <div
              key={msg.id}
              className={`flex gap-3 max-w-4xl ${isUser ? 'ml-auto flex-row-reverse' : 'mr-auto'}`}
            >
              {/* Avatar */}
              <div
                className={`w-8 h-8 rounded-xl shrink-0 flex items-center justify-center shadow-2xs ${
                  isUser
                    ? 'bg-indigo-600 text-white'
                    : 'bg-slate-900 text-indigo-400 border border-slate-800'
                }`}
              >
                {isUser ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
              </div>

              {/* Message Bubble */}
              <div
                className={`rounded-2xl px-4 py-3.5 text-xs sm:text-sm leading-relaxed max-w-[88%] shadow-xs ${
                  isUser
                    ? 'bg-indigo-600 text-white rounded-tr-xs'
                    : 'bg-white text-slate-800 border border-slate-200/90 rounded-tl-xs'
                }`}
              >
                {/* Body Content */}
                <div className="whitespace-pre-wrap space-y-2">{msg.text}</div>

                {/* Agent Proactive Clarifying Question Box */}
                {!isUser && msg.clarification && (
                  <div className="mt-3.5 p-3.5 rounded-xl bg-amber-50/90 border border-amber-300 text-amber-950 text-xs">
                    <div className="font-bold flex items-center gap-1.5 text-amber-900 mb-1">
                      <HelpCircle className="w-4 h-4 text-amber-600 shrink-0" />
                      <span>Agent Clarifying Question:</span>
                    </div>
                    <p className="text-amber-900 font-medium leading-relaxed">{msg.clarification}</p>
                    <div className="mt-2.5 flex flex-wrap gap-2">
                      <button
                        onClick={() => handleClarificationClick(msg.clarification || '')}
                        className="px-3 py-1 bg-white hover:bg-amber-100 text-amber-900 font-semibold rounded-lg border border-amber-300 transition text-[11px] shadow-2xs cursor-pointer flex items-center gap-1"
                      >
                        <MessageSquare className="w-3 h-3 text-amber-700" />
                        <span>Answer this clarification</span>
                      </button>
                    </div>
                  </div>
                )}

                {/* Grounded MS SQL Chunks */}
                {!isUser && msg.retrievedChunks && msg.retrievedChunks.length > 0 && (
                  <div className="mt-3.5 pt-3 border-t border-slate-100 text-[11px]">
                    <div className="font-semibold text-slate-700 flex items-center gap-1 mb-1.5">
                      <FileText className="w-3.5 h-3.5 text-indigo-600" />
                      <span>Retrieved from MS SQL Server (Cosine Similarity):</span>
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      {msg.retrievedChunks.map((chunk) => (
                        <div
                          key={chunk.ChunkId}
                          className="bg-indigo-50/80 text-indigo-900 border border-indigo-200/80 rounded-md px-2 py-1 font-mono text-[10px]"
                        >
                          <span className="font-bold">{chunk.FileName}</span> (Part {chunk.ChunkIndex + 1}) —{' '}
                          <span className="text-emerald-700 font-semibold">
                            {(chunk.SimilarityScore * 100).toFixed(0)}% match
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Footer Metadata */}
                <div
                  className={`mt-2 flex items-center justify-between gap-3 text-[10px] ${
                    isUser ? 'text-indigo-200' : 'text-slate-400'
                  }`}
                >
                  <span className="flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    <span>{msg.timestamp}</span>
                  </span>
                  {!isUser && msg.searchTimeMs !== undefined && (
                    <span className="font-mono text-[10px] text-slate-500">
                      MS SQL: {msg.searchTimeMs}ms • LLM: {msg.llmTimeMs}ms
                    </span>
                  )}
                </div>
              </div>
            </div>
          );
        })}

        {isLoading && (
          <div className="flex gap-3 max-w-xl mr-auto">
            <div className="w-8 h-8 rounded-xl shrink-0 bg-slate-900 text-indigo-400 flex items-center justify-center border border-slate-800">
              <Bot className="w-4 h-4 animate-pulse" />
            </div>
            <div className="bg-white border border-slate-200 rounded-2xl rounded-tl-xs px-4 py-3 shadow-xs text-xs text-slate-600 flex items-center gap-3">
              <div className="w-4 h-4 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin shrink-0" />
              <span>
                1. Vectorizing question &rarr; 2. Querying MS SQL Server (<code className="font-mono text-[11px] text-indigo-700">VECTOR_DISTANCE</code>) &rarr; 3. Prompting Gemini AI...
              </span>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Starter Prompts */}
      <div className="px-4 py-2 bg-slate-50 border-t border-slate-200/80 overflow-x-auto flex gap-2">
        {starterPrompts.map((p, idx) => (
          <button
            key={idx}
            onClick={() => handleSend(p)}
            className="text-[11px] font-medium px-3 py-1 rounded-full bg-white hover:bg-indigo-50 border border-slate-200 text-slate-700 hover:text-indigo-700 whitespace-nowrap transition cursor-pointer shadow-2xs"
          >
            💡 {p}
          </button>
        ))}
      </div>

      {/* Input Bar */}
      <div className="p-3 sm:p-4 bg-white border-t border-slate-200">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSend();
          }}
          className="flex items-center gap-2"
        >
          <input
            type="text"
            value={inputQuery}
            onChange={(e) => setInputQuery(e.target.value)}
            placeholder="Ask questions about SLA, employee benefits, or disaster recovery runbooks..."
            className="flex-1 px-4 py-2.5 text-xs sm:text-sm bg-slate-50 border border-slate-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white transition"
          />
          <button
            type="submit"
            disabled={isLoading || !inputQuery.trim()}
            className="flex items-center gap-1.5 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white text-xs sm:text-sm font-semibold rounded-xl transition cursor-pointer shrink-0 shadow-xs"
          >
            <Send className="w-4 h-4" />
            <span className="hidden sm:inline">Ask Agent</span>
          </button>
        </form>
      </div>
    </div>
  );
};

// Angular/src/app/components/agent-qa/agent-qa.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { RagApiService } from '../../services/rag-api.service';
import { ChatMessage } from '../../models/rag.models';

@Component({
  selector: 'app-agent-qa',
  standalone: true,
  imports: [CommonModule, FormsModule, MatInputModule, MatButtonModule, MatIconModule, MatChipsModule],
  template: `
    <div class="chat-container flex flex-col h-[700px] bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-xs">
      <!-- Chat Header -->
      <div class="p-4 bg-slate-900 text-white flex items-center justify-between border-b border-slate-800">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-xl bg-indigo-600 flex items-center justify-center text-white">
            <mat-icon class="!w-5 !h-5 !text-xl">psychology</mat-icon>
          </div>
          <div>
            <h3 class="font-bold text-sm">Agent Q&amp;A (Vector + Gemini)</h3>
            <p class="text-[11px] text-slate-400">
              Flow: Query &rarr; Vectorize &rarr; MS SQL Cosine Search &rarr; Gemini LLM &rarr; Response
            </p>
          </div>
        </div>
      </div>

      <!-- Messages Stream -->
      <div class="flex-1 overflow-y-auto p-4 sm:p-6 space-y-4 bg-slate-50/50">
        <div *ngFor="let msg of messages()" [ngClass]="msg.role === 'user' ? 'text-right' : 'text-left'">
          <div [ngClass]="msg.role === 'user' ? 'bg-indigo-600 text-white ml-auto' : 'bg-white text-slate-800 border border-slate-200'"
               class="inline-block max-w-[85%] rounded-2xl px-4 py-3 text-xs sm:text-sm shadow-xs">
            <p class="whitespace-pre-line leading-relaxed">{{ msg.text }}</p>

            <!-- Agent Clarifying Question Box -->
            <div *ngIf="msg.clarification" class="mt-3 p-3.5 bg-amber-50 border border-amber-300 rounded-xl text-amber-950 text-xs">
              <div class="font-bold flex items-center gap-1.5 text-amber-900 mb-1">
                <mat-icon class="!w-4 !h-4 !text-base">help_outline</mat-icon>
                <span>Agent Clarifying Question:</span>
              </div>
              <p class="font-medium">{{ msg.clarification }}</p>
              <div class="mt-2.5 flex gap-2">
                <button mat-stroked-button class="!text-[11px] !bg-white !text-amber-900" (click)="replyWithClarification('Please provide the full policy guidelines.')">
                  Provide full policy
                </button>
              </div>
            </div>

            <!-- Grounded Citations from MS SQL Server -->
            <div *ngIf="msg.retrievedChunks?.length" class="mt-3 pt-2.5 border-t border-slate-100 text-[11px] text-slate-500">
              <span class="font-semibold text-slate-700">MS SQL Server Vectors:</span>
              <div class="flex flex-wrap gap-1.5 mt-1">
                <span *ngFor="let c of msg.retrievedChunks" class="bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded border border-indigo-200 text-[10px] font-mono">
                  {{ c.fileName }} (Part {{ c.chunkIndex + 1 }}) - {{ (c.similarityScore * 100).toFixed(0) }}% match
                </span>
              </div>
            </div>
          </div>
        </div>

        <div *ngIf="isLoading()" class="flex items-center gap-2 text-xs text-slate-500 italic p-3 bg-white rounded-xl border border-slate-200 inline-block shadow-2xs">
          <span>Querying MS SQL vector store &amp; generating grounded Gemini response...</span>
        </div>
      </div>

      <!-- Quick Suggested Prompts -->
      <div class="px-4 py-2 bg-slate-50 border-t border-slate-200 overflow-x-auto flex gap-2">
        <button *ngFor="let p of starterPrompts" (click)="sendMessage(p)" 
                class="text-[11px] font-medium px-2.5 py-1 rounded-full bg-white hover:bg-indigo-50 border border-slate-200 text-slate-700 hover:text-indigo-700 whitespace-nowrap transition cursor-pointer">
          💡 {{ p }}
        </button>
      </div>

      <!-- Input Bar -->
      <div class="p-3 bg-white border-t border-slate-200 flex gap-2">
        <input [(ngModel)]="userQuery" (keyup.enter)="sendMessage()"
               placeholder="Ask questions about SLA, employee leave, or incident response..."
               class="flex-1 px-4 py-2.5 text-xs sm:text-sm border border-slate-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500" />
        <button mat-raised-button color="primary" class="!bg-indigo-600 !text-white !font-semibold !rounded-xl" (click)="sendMessage()" [disabled]="isLoading() || !userQuery.trim()">
          <mat-icon>send</mat-icon> Ask Agent
        </button>
      </div>
    </div>
  `
})
export class AgentQaComponent {
  private ragService = inject(RagApiService);
  messages = signal<ChatMessage[]>([
    {
      id: 'welcome',
      role: 'agent',
      text: `Hello! I am your Enterprise RAG Agent.
When you ask a question:
1. Your question is converted into a vector format.
2. It queries our MS SQL Server database to fetch existing vectors and compute cosine distances.
3. The retrieved vector chunks are forwarded to Gemini AI (LLM).
4. I formulate an authoritative response with citations and ask clarifying questions when appropriate.`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  userQuery = '';
  isLoading = signal(false);

  starterPrompts = [
    'What is our disaster recovery RPO and RTO SLA target?',
    'How many weeks of fully paid parental leave are primary caregivers entitled to?',
    'What is the network isolation protocol during a security breach?',
    'What wellness stipends and remote allowances do employees receive?'
  ];

  sendMessage(overrideQuery?: string) {
    const query = overrideQuery || this.userQuery;
    if (!query.trim()) return;
    this.userQuery = '';

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      text: query,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    this.messages.update((prev) => [...prev, userMsg]);
    this.isLoading.set(true);

    this.ragService.askAgent({ query, topK: 4 }).subscribe({
      next: (res) => {
        const agentMsg: ChatMessage = {
          id: `agent-${Date.now()}`,
          role: 'agent',
          text: res.answer,
          clarification: res.clarificationQuestion,
          retrievedChunks: res.retrievedChunks,
          sqlExecutionQuery: res.sqlExecutionQuery,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        };
        this.messages.update((prev) => [...prev, agentMsg]);
        this.isLoading.set(false);
      },
      error: (err) => {
        this.messages.update((prev) => [
          ...prev,
          {
            id: `err-${Date.now()}`,
            role: 'agent',
            text: 'Error in RAG pipeline: ' + err.message,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
          }
        ]);
        this.isLoading.set(false);
      }
    });
  }

  replyWithClarification(text: string) {
    this.sendMessage(text);
  }
}
